import {
  BusinessProfile,
  StructuredBusinessProfile,
  DiscoveredOpportunity,
  BuyingSignal,
  Lead,
  CallSession,
  Opportunity,
  DashboardOverview,
} from './types';

export const MOCK_DISCOVERED_OPPORTUNITIES: DiscoveredOpportunity[] = [
  {
    id: 'disc-001',
    company: {
      name: 'Example Manufacturing Ltd.',
      domain: 'examplemanufacturing.com',
      industry: 'Manufacturing & Industrial',
      location: 'Chicago, IL, United States',
      employee_count: '250-500',
      revenue_estimate: '$45M ARR',
    },
    requirement: {
      title: 'Microsoft 365 / SharePoint migration and support',
      description:
        'Looking for a company to migrate our Microsoft 365 environment to SharePoint and provide ongoing support.',
      requirement_type: 'Cloud Migration & Support',
      urgency: 'High',
      budget_hint: '$30k - $50k initial project + managed support',
    },
    source: {
      platform: 'Public Requirement Source',
      original_url: 'https://public-procurement.demo/rfp/m365-sharepoint-0921',
      verified_public: true,
      confidence_score: 0.96,
    },
    detected_date: '2026-03-08T10:30:00Z',
    intent_level: 'High',
    match_score: 94,
    matched_offering: 'Enterprise Cloud Migration & Managed Support Suite',
    match_rationale:
      'Direct requirement match for Microsoft 365 environment consolidation, SharePoint data architecture, and ongoing Tier 2/3 engineering support.',
    status: 'New',
  },
  {
    id: 'disc-002',
    company: {
      name: 'Acuity Payments Global',
      domain: 'acuitypayments.com',
      industry: 'Digital Banks & FinTech',
      location: 'New York, NY, United States',
      employee_count: '180-300',
      revenue_estimate: '$32M ARR',
    },
    requirement: {
      title: 'Real-time AML monitoring & synthetic identity fraud detection',
      description:
        'Seeking an autonomous transaction monitoring platform to detect synthetic identity fraud and anomalous ledger movements in real-time before our upcoming FINRA regulatory audit.',
      requirement_type: 'AML & Fraud Prevention',
      urgency: 'High',
      budget_hint: '$60k - $90k ARR',
    },
    source: {
      platform: 'Public RFP Portal',
      original_url: 'https://procurement.fintech-leads.demo/rfp/aml-2026-081',
      verified_public: true,
      confidence_score: 0.97,
    },
    detected_date: '2026-03-09T08:15:00Z',
    intent_level: 'High',
    match_score: 96,
    matched_offering: 'PulseSentry AML & Real-time Identity Detector',
    match_rationale:
      'Urgent regulatory deadline requiring automated transaction monitoring and sub-10ms synthetic identity verification across payment rails.',
    status: 'New',
  },
  {
    id: 'disc-003',
    company: {
      name: 'FinTrack Analytics',
      domain: 'fintrack.io',
      industry: 'FinTech / Financial Data',
      location: 'San Francisco, CA, United States',
      employee_count: '180',
      revenue_estimate: '$28M ARR',
    },
    requirement: {
      title: 'SOC 2 Type II audit automation & AWS multi-account IAM governance',
      description:
        'Urgent requirement for automated auditor evidence collection and least-privilege IAM right-sizing to unblock two pending Tier-1 enterprise banking contracts.',
      requirement_type: 'Compliance & Security Posture',
      urgency: 'High',
      budget_hint: '$35k - $50k ARR',
    },
    source: {
      platform: 'B2B Procurement Feed',
      original_url: 'https://techprocure.demo/rfp/soc2-fintrack-492',
      verified_public: true,
      confidence_score: 0.95,
    },
    detected_date: '2026-03-07T14:20:00Z',
    intent_level: 'High',
    match_score: 95,
    matched_offering: 'AuditBot 360 & Enterprise Compliance Suite',
    match_rationale:
      'Series B funded scaleup with immediate compliance roadblock; requires automated evidence gathering and agentic Terraform remediation.',
    status: 'New',
  },
  {
    id: 'disc-004',
    company: {
      name: 'HealthBridge Care',
      domain: 'healthbridge.co',
      industry: 'Healthcare & Telehealth',
      location: 'Boston, MA, United States',
      employee_count: '320',
      revenue_estimate: '$45M ARR',
    },
    requirement: {
      title: 'European GDPR data residency & ISO 27001 telehealth readiness',
      description:
        'RFP for pre-certified ISO 27001 evidence automation and cross-border GDPR health data sovereignty monitoring for European telehealth clinic expansion.',
      requirement_type: 'Compliance & Data Sovereignty',
      urgency: 'High',
      budget_hint: '$40k - $60k ARR',
    },
    source: {
      platform: 'Public Regulatory Filing',
      original_url: 'https://regulatory-filings.health.demo/notices/iso-gdpr-2026',
      verified_public: true,
      confidence_score: 0.91,
    },
    detected_date: '2026-03-06T11:00:00Z',
    intent_level: 'High',
    match_score: 92,
    matched_offering: 'AuditBot 360 (Healthcare/ISO Edition)',
    match_rationale:
      'Strict regulatory timetable for clinical operation in Germany and France with heavy data privacy requirements.',
    status: 'New',
  },
  {
    id: 'disc-005',
    company: {
      name: 'DataSpire Systems',
      domain: 'dataspire.com',
      industry: 'Enterprise Data & Analytics',
      location: 'Austin, TX, United States',
      employee_count: '540',
      revenue_estimate: '$80M ARR',
    },
    requirement: {
      title: 'Automated cloud IAM role right-sizing & toxic permission mapping',
      description:
        'Experiencing cloud IAM role explosion following AWS multi-account migration. Need agentless visibility into dormant credentials and automated least-privilege role right-sizing.',
      requirement_type: 'Cloud Security & IAM',
      urgency: 'Medium',
      budget_hint: '$30k - $45k ARR',
    },
    source: {
      platform: 'Open B2B Procurement Portal',
      original_url: 'https://openrfp.cloudinfra.demo/req/dataspire-iam-03',
      verified_public: true,
      confidence_score: 0.88,
    },
    detected_date: '2026-03-05T16:00:00Z',
    intent_level: 'Medium',
    match_score: 88,
    matched_offering: 'Zero-Trust Identity Sentinel (CIEM)',
    match_rationale:
      'Operational bottleneck caused by over-privileged roles and lack of cross-account IAM visibility.',
    status: 'New',
  },
  {
    id: 'disc-006',
    company: {
      name: 'OmniRetail Global',
      domain: 'omniretail.com',
      industry: 'E-Commerce & Retail Tech',
      location: 'London, United Kingdom',
      employee_count: '850',
      revenue_estimate: '$120M ARR',
    },
    requirement: {
      title: 'Continuous multi-cloud audit readiness ahead of Q4 IPO',
      description:
        'Board audit committee mandated continuous multi-cloud security monitoring and automated evidence collection across AWS and Azure environments before IPO filing.',
      requirement_type: 'Compliance & Audit',
      urgency: 'High',
      budget_hint: '$50k - $80k ARR',
    },
    source: {
      platform: 'Public Corporate Tender Portal',
      original_url: 'https://tenders.omni.demo/rfp/ipo-audit-readiness',
      verified_public: true,
      confidence_score: 0.93,
    },
    detected_date: '2026-03-08T09:00:00Z',
    intent_level: 'High',
    match_score: 91,
    matched_offering: 'AuditBot 360 & Posture Guard Enterprise',
    match_rationale:
      'Hard deadline driven by public IPO filing with external auditor committee scrutiny.',
    status: 'New',
  },
];

export const MOCK_STRUCTURED_PROFILE: StructuredBusinessProfile = {
  company_name: 'Apex Enterprise & Wholesale Solutions',
  company_website: 'https://apexwholesale.example.com',
  company_summary:
    'Apex delivers an integrated enterprise supply, wholesale distribution, and commercial procurement platform connecting verified manufacturers with retail, commercial, and enterprise buyers.',
  products_services: [
    'Modal Silk Sarees & Ethnic Textiles Wholesale',
    'Commercial Sourcing & Bulk Procurement',
    'Enterprise Manufacturing & Distribution Logistics',
  ],
  target_customers: [
    'Retail Chain Owners & Boutique Buyers',
    'Procurement Directors & Category Managers',
    'Wholesale Distributors & Regional Merchants',
  ],
  target_industries: [
    'Apparel & Fashion Boutiques',
    'Retail Chains & Department Stores',
    'Textiles & Garment Sourcing',
  ],
  target_locations: [
    'India (Mumbai, Delhi, Bangalore, Surat)',
    'North America & United Kingdom',
    'Global Export Hubs',
  ],
  ideal_customer_profile:
    'Retail chains, boutique store owners, and corporate procurement heads seeking dependable, high-quality bulk supplies with verified lead times and competitive wholesale pricing.',
  keywords: [
    'modal silk sarees',
    'bulk wholesale textile',
    'boutique sourcing',
    'b2b supply order',
    'commercial catalog procurement',
  ],
  buying_signals: [
    'Seasonal festive inventory stockup mandate',
    'Procurement RFP for 500+ unit bulk catalog supply',
    'Expansion into new boutique retail locations',
    'Vendor consolidation for guaranteed dispatch timelines',
  ],
  is_demo_mode: false,
  source_files: [],
  updated_at: '2026-03-08T12:00:00Z',
};

export const MOCK_BUSINESS_PROFILE: BusinessProfile = {
  id: 'biz-apex-wholesale',
  company_name: 'Apex Enterprise & Wholesale Solutions',
  domain: 'apexwholesale.example.com',
  industry: 'B2B Wholesale & Supply Chain Distribution',
  headline: 'Commercial Supply Chain & Verified B2B Wholesale Distribution',
  description:
    'Apex delivers an integrated enterprise supply, wholesale distribution, and commercial procurement platform connecting verified manufacturers with retail, commercial, and enterprise buyers.',
  value_propositions: [
    'Guaranteed direct-from-manufacturer wholesale pricing with zero intermediary markups.',
    'Fast turnaround on bulk orders with verified quality audits before dispatch.',
    'Full transparency on unit economics, volume tiered pricing, and shipping schedules.',
  ],
  differentiators: [
    'Direct Factory Relationships: Consistent quality and bulk customization capacity.',
    'Transparent Pricing: Immediate unit and lot quotes with no hidden freight surcharges.',
    'Dedicated Account Management: End-to-end order tracking and dedicated dispatch coordinators.',
  ],
  products: [
    {
      id: 'prod-textiles',
      name: 'Modal Silk Sarees & Ethnic Textiles',
      category: 'Textiles & Apparel Wholesale',
      tagline: 'Premium artisan silk sarees for retail boutiques and chain stores',
      description:
        'High-density weave modal silk sarees in authentic artisanal prints, packaged for immediate boutique and department store retail.',
      key_features: [
        '100% genuine modal silk yarn',
        'Custom color palettes and exclusive regional designs',
        'Volume-tiered wholesale discounts for 100+ unit orders',
        'Standardized batch quality inspection report',
      ],
      target_pain_points: [
        'Inconsistent yarn quality and unverified dye fastness from unvetted vendors',
        'Unpredictable delivery times ahead of festive peak selling seasons',
        'High minimum order quantities from traditional mills',
      ],
      pricing_tier: '₹750 – ₹1,200 per piece (Volume Tiered)',
      ideal_customer_size: 'Retail Boutiques, Departmental Chains, E-commerce Sellers',
      proof_point: 'Supplied over 15,000 sarees to 45 regional boutiques with 99.4% on-time dispatch rate.',
    },
    {
      id: 'prod-sourcing',
      name: 'Commercial Sourcing & Bulk Procurement',
      category: 'Supply Chain & Sourcing',
      tagline: 'End-to-end procurement and contract manufacturing fulfillment',
      description:
        'Custom procurement services matching commercial buyers with verified fabrication and production facilities.',
      key_features: [
        'Dedicated procurement team for RFP matching',
        'Pre-shipment batch testing and compliance documentation',
        'Milestone-based payment terms and logistics clearing',
      ],
      target_pain_points: [
        'Complex supply chain logistics and customs hurdles',
        'Lack of vendor accountability for late deliveries',
      ],
      pricing_tier: 'Custom Commercial Quote',
      ideal_customer_size: 'Mid-to-Large Enterprises',
      proof_point: 'Fulfilled enterprise orders worth over ₹2.4 Crores across 12 product categories.',
    },
  ],
  target_personas: [
    {
      id: 'per-buyer',
      title: 'Head of Purchasing / Retail Buyer',
      seniority: 'Director / Owner',
      department: 'Procurement & Merchandising',
      key_priorities: [
        'Securing guaranteed supply ahead of seasonal demand surges',
        'Achieving healthy gross margins with competitive wholesale unit pricing',
        'Ensuring repeatable quality across all dispatched lots',
      ],
      common_objections: [
        'We already have established local distributors',
        'Concerned about delivery lead times for custom lots',
        'Need to inspect physical fabric swatches before committing to 500+ units',
      ],
    },
  ],
  collateral_docs: [
    'Apex_Wholesale_Catalog_2026.pdf',
    'Fabric_Quality_Inspection_Standards.pdf',
  ],
};

export const MOCK_SIGNALS: BuyingSignal[] = [
  {
    id: 'sig-001',
    company_name: 'FinTrack Analytics',
    domain: 'fintrack.io',
    signal_type: 'funding',
    title: 'Closed $38M Series B Funding Round led by Bessemer',
    summary:
      'FinTrack raised $38M to scale their real-time financial ledger API and expand into Tier 1 banking clients.',
    source: 'TechCrunch & Crunchbase',
    detected_at: '2026-03-01T10:15:00Z',
    confidence_score: 0.96,
    urgency_level: 'High',
    urgency_score: 94,
    processed: true,
    lead_id: 'lead-001',
  },
  {
    id: 'sig-002',
    company_name: 'FinTrack Analytics',
    domain: 'fintrack.io',
    signal_type: 'hiring_surge',
    title: 'Actively hiring Head of Information Security & 4 Senior DevOps Engineers',
    summary:
      'FinTrack posted job openings specifically requiring SOC 2 Type II experience and AWS multi-account governance.',
    source: 'LinkedIn Talent Insights',
    detected_at: '2026-03-03T14:20:00Z',
    confidence_score: 0.92,
    urgency_level: 'High',
    urgency_score: 91,
    processed: true,
    lead_id: 'lead-001',
  },
  {
    id: 'sig-003',
    company_name: 'HealthBridge Care',
    domain: 'healthbridge.co',
    signal_type: 'expansion',
    title: 'Announced EU Expansion & Telehealth Clinic Rollout',
    summary:
      'HealthBridge is launching telehealth services in Germany and France, requiring immediate GDPR and ISO 27001 certification.',
    source: 'Press Release & Regulatory Filing',
    detected_at: '2026-03-04T09:00:00Z',
    confidence_score: 0.89,
    urgency_level: 'High',
    urgency_score: 88,
    processed: true,
    lead_id: 'lead-002',
  },
  {
    id: 'sig-004',
    company_name: 'DataSpire Systems',
    domain: 'dataspire.com',
    signal_type: 'tech_stack_change',
    title: 'Migrated Core Data Warehouse from On-Premises to AWS Multi-Account',
    summary:
      'CTO published a technical engineering blog discussing complex cloud IAM role explosion during AWS migration.',
    source: 'Engineering Blog & GitHub',
    detected_at: '2026-03-05T16:45:00Z',
    confidence_score: 0.85,
    urgency_level: 'Medium',
    urgency_score: 76,
    processed: true,
    lead_id: 'lead-003',
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-001',
    company_name: 'FinTrack Analytics',
    domain: 'fintrack.io',
    industry: 'Fintech / Financial Data',
    employee_count: '180',
    estimated_revenue: '$28M ARR',
    location: 'San Francisco, CA & Remote',
    tech_stack: ['AWS', 'Kubernetes', 'PostgreSQL', 'Terraform', 'GitHub Actions'],
    signals_count: 2,
    signals_summary: [
      'Series B $38M funding led by Bessemer (High Urgency)',
      'Urgent hiring for Head of Security & DevOps with SOC 2 mandate',
    ],
    contacts: [
      {
        name: 'Marcus Vance',
        title: 'VP of Engineering & Acting Head of Security',
        role_level: 'VP',
        email: 'm.vance@fintrack.io',
        phone: '+1 (415) 890-3412',
        linkedin_url: 'https://linkedin.com/in/marcus-vance-fintrack',
        decision_authority: 'Primary',
      },
    ],
    primary_contact: {
      name: 'Marcus Vance',
      title: 'VP of Engineering & Acting Head of Security',
      role_level: 'VP',
      email: 'm.vance@fintrack.io',
      phone: '+1 (415) 890-3412',
      linkedin_url: 'https://linkedin.com/in/marcus-vance-fintrack',
      decision_authority: 'Primary',
    },
    match: {
      product_id: 'prod-auditbot',
      product_name: 'AuditBot 360',
      fit_score: 96,
      match_tier: 'Strong',
      reasoning:
        'FinTrack’s recent $38M round and enterprise banking expansion require fast SOC 2 Type II certification.',
      aligned_features: [
        'Automated SOC 2 Type II evidence gathering',
        'Continuous AWS multi-account scanning',
        'Direct auditor portal integration',
      ],
      suggested_pitch:
        'Help FinTrack secure Tier 1 banking contracts without taking 4 months of engineering time to pass SOC 2 Type II.',
    },
    intent: {
      overall_score: 94,
      grade: 'A',
      urgency_component: 95,
      fit_component: 98,
      authority_component: 90,
      timing_component: 92,
      buying_readiness: 'Immediate (0-30 days)',
      key_drivers: [
        'Fresh capital deployment ($38M Series B)',
        'Active job req for security leadership with immediate audit deliverables',
        'Enterprise customers blocking deals pending SOC 2 report',
      ],
    },
    status: 'Interested',
    created_at: '2026-03-01T12:00:00Z',
    updated_at: '2026-03-08T09:30:00Z',
    notes: 'Engaged with AI Sales Agent. Agreed to technical demo.',
  },
  {
    id: 'lead-002',
    company_name: 'HealthBridge Care',
    domain: 'healthbridge.co',
    industry: 'Healthcare / Telemedicine',
    employee_count: '320',
    estimated_revenue: '$45M ARR',
    location: 'Boston, MA',
    tech_stack: ['GCP', 'Kubernetes', 'React Native', 'BigQuery', 'Terraform'],
    signals_count: 1,
    signals_summary: ['Announced EU expansion needing ISO 27001 and GDPR compliance'],
    contacts: [
      {
        name: 'Dr. Aris Thorne',
        title: 'Chief Technology Officer',
        role_level: 'C-Level',
        email: 'aris.thorne@healthbridge.co',
        phone: '+1 (617) 555-0192',
        linkedin_url: 'https://linkedin.com/in/aris-thorne',
        decision_authority: 'Primary',
      },
    ],
    primary_contact: {
      name: 'Dr. Aris Thorne',
      title: 'Chief Technology Officer',
      role_level: 'C-Level',
      email: 'aris.thorne@healthbridge.co',
      phone: '+1 (617) 555-0192',
      linkedin_url: 'https://linkedin.com/in/aris-thorne',
      decision_authority: 'Primary',
    },
    match: {
      product_id: 'prod-auditbot',
      product_name: 'AuditBot 360',
      fit_score: 91,
      match_tier: 'Strong',
      reasoning:
        'Expanding into European telehealth requires ISO 27001 & GDPR audit compliance within 90 days.',
      aligned_features: ['ISO 27001 automation', 'GDPR data residency monitoring', 'HIPAA cross-walk'],
      suggested_pitch:
        'Fast-track HealthBridge’s European clinic launch with pre-certified ISO 27001 auditor packages.',
    },
    intent: {
      overall_score: 88,
      grade: 'A',
      urgency_component: 90,
      fit_component: 92,
      authority_component: 88,
      timing_component: 84,
      buying_readiness: 'High (30-60 days)',
      key_drivers: [
        'Strict regulatory deadline for German & French clinic operations',
        'High sensitivity to healthcare data breaches',
      ],
    },
    status: 'Outreach_Ready',
    created_at: '2026-03-04T10:00:00Z',
    updated_at: '2026-03-07T14:15:00Z',
  },
  {
    id: 'lead-003',
    company_name: 'DataSpire Systems',
    domain: 'dataspire.com',
    industry: 'Enterprise Data / Analytics',
    employee_count: '540',
    estimated_revenue: '$80M ARR',
    location: 'Austin, TX',
    tech_stack: ['AWS', 'Snowflake', 'Databricks', 'Kubernetes', 'Okta'],
    signals_count: 1,
    signals_summary: [
      'Migrated to AWS multi-account; blogged about cloud IAM permission explosion',
    ],
    contacts: [
      {
        name: 'Kavita Raman',
        title: 'Head of Cloud Infrastructure & SecOps',
        role_level: 'Director',
        email: 'k.raman@dataspire.com',
        phone: '+1 (512) 441-9081',
        decision_authority: 'Influencer',
      },
    ],
    primary_contact: {
      name: 'Kavita Raman',
      title: 'Head of Cloud Infrastructure & SecOps',
      role_level: 'Director',
      email: 'k.raman@dataspire.com',
      phone: '+1 (512) 441-9081',
      decision_authority: 'Influencer',
    },
    match: {
      product_id: 'prod-ciem',
      product_name: 'Zero-Trust Identity Sentinel',
      fit_score: 94,
      match_tier: 'Strong',
      reasoning:
        'DataSpire explicitly mentioned IAM role explosion and toxic privilege paths in their AWS multi-account environment.',
      aligned_features: [
        'Toxic permission mapping',
        'Least-privilege role right-sizing',
        'Okta-to-AWS role sync',
      ],
      suggested_pitch:
        'Automatically prune dormant permissions and enforce least-privilege IAM across AWS multi-account organizations without breaking production.',
    },
    intent: {
      overall_score: 84,
      grade: 'B',
      urgency_component: 80,
      fit_component: 95,
      authority_component: 82,
      timing_component: 78,
      buying_readiness: 'High (30-60 days)',
      key_drivers: [
        'Publicly acknowledged operational bottleneck around cloud IAM',
        'High security posture requirement handling enterprise client telemetry',
      ],
    },
    status: 'Matched',
    created_at: '2026-03-05T17:00:00Z',
    updated_at: '2026-03-06T11:00:00Z',
  },
  {
    id: 'lead-004',
    company_name: 'PayMatrix Global',
    domain: 'paymatrix.net',
    industry: 'Payments / RegTech',
    employee_count: '850',
    estimated_revenue: '$140M ARR',
    location: 'New York, NY',
    tech_stack: ['AWS', 'Azure', 'Kubernetes', 'Kafka', 'Datadog'],
    signals_count: 1,
    signals_summary: [
      'Appointed new CRSO tasked with Zero Trust modernization and hybrid posture',
    ],
    contacts: [
      {
        name: 'Elena Rostova',
        title: 'Chief Risk & Security Officer',
        role_level: 'C-Level',
        email: 'elena.rostova@paymatrix.net',
        phone: '+1 (212) 779-1102',
        decision_authority: 'Primary',
      },
    ],
    primary_contact: {
      name: 'Elena Rostova',
      title: 'Chief Risk & Security Officer',
      role_level: 'C-Level',
      email: 'elena.rostova@paymatrix.net',
      phone: '+1 (212) 779-1102',
      decision_authority: 'Primary',
    },
    match: {
      product_id: 'prod-sourcing',
      product_name: 'Enterprise Procurement Guard',
      fit_score: 87,
      match_tier: 'Strong',
      reasoning:
        'New CRSO Elena is revamping vendor risk and hybrid cloud visibility following recent corporate acquisition.',
      aligned_features: [
        'Unified AWS and Azure security posture',
        'Agentic Terraform remediation',
        'Executive board reporting',
      ],
      suggested_pitch:
        'Give the executive board 100% real-time posture visibility across newly merged AWS & Azure accounts.',
    },
    intent: {
      overall_score: 81,
      grade: 'B',
      urgency_component: 82,
      fit_component: 88,
      authority_component: 92,
      timing_component: 72,
      buying_readiness: 'Exploring (60-90 days)',
      key_drivers: [
        'First 90-day executive mandate to review security toolchain',
        'Large enterprise budget availability',
      ],
    },
    status: 'Enriched',
    created_at: '2026-03-06T12:00:00Z',
    updated_at: '2026-03-07T16:00:00Z',
  },
];

export const MOCK_CALLS: CallSession[] = [];

export const MOCK_OPPORTUNITIES: Opportunity[] = [];

export const MOCK_OVERVIEW: DashboardOverview = {
  kpis: {
    active_buying_signals: 0,
    high_urgency_signals: 0,
    total_leads: 0,
    grade_a_leads: 0,
    ai_calls_conducted: 0,
    meetings_secured: 0,
    qualified_opportunities: 0,
    pipeline_value_estimate: '$0',
    average_response_rate: '0%',
    ai_qualification_rate: '0%',
  },
  funnel: [
    { stage: 'Buying Signals', label: 'Signals', count: 0, percentage: 0 },
    { stage: 'Qualified Leads', label: 'Leads', count: 0, percentage: 0 },
    { stage: 'AI Outreach', label: 'Outreach', count: 0, percentage: 0 },
    { stage: 'Opportunities', label: 'Opportunities', count: 0, percentage: 0 },
  ],
  conversion_rates: {
    signal_to_lead: 0,
    lead_to_opportunity: 0,
    overall_conversion: 0,
    counts: { signals: 0, leads: 0, outreach: 0, opportunities: 0 },
  },
  buying_signals_summary: {
    total_active_signals: 0,
    signals: [],
  },
  opportunity_summary: {
    total_count: 0,
    has_real_values: false,
    pipeline_value: null,
    formatted_pipeline_value: null,
    stage_breakdown: [],
    opportunities: [],
  },
  top_buying_signals: [],
  high_priority_leads: [],
  recent_opportunities: [],
};
