import {
  BusinessProfile,
  StructuredBusinessProfile,
  DiscoveredOpportunity,
  BuyingSignal,
  Lead,
  CallSession,
  Campaign,
  Opportunity,
  DashboardOverview,
} from './types';

export const MOCK_DISCOVERED_OPPORTUNITIES: DiscoveredOpportunity[] = [
  {
    id: 'disc-001',
    company: {
      name: 'Example Manufacturing Ltd.',
      domain: 'examplemanufacturing.com',
      industry: 'Manufacturing & Industrial',
      location: 'Chicago, IL, United States',
      employee_count: '250-500',
      revenue_estimate: '$45M ARR',
    },
    requirement: {
      title: 'Microsoft 365 / SharePoint migration and support',
      description:
        'Looking for a company to migrate our Microsoft 365 environment to SharePoint and provide ongoing support.',
      requirement_type: 'Cloud Migration & Support',
      urgency: 'High',
      budget_hint: '$30k - $50k initial project + managed support',
    },
    source: {
      platform: 'Public Requirement Source',
      original_url: 'https://public-procurement.demo/rfp/m365-sharepoint-0921',
      verified_public: true,
      confidence_score: 0.96,
    },
    detected_date: '2026-03-08T10:30:00Z',
    intent_level: 'High',
    match_score: 94,
    matched_offering: 'Enterprise Cloud Migration & Managed Support Suite',
    match_rationale:
      'Direct requirement match for Microsoft 365 environment consolidation, SharePoint data architecture, and ongoing Tier 2/3 engineering support.',
    status: 'New',
  },
  {
    id: 'disc-002',
    company: {
      name: 'Acuity Payments Global',
      domain: 'acuitypayments.com',
      industry: 'Digital Banks & FinTech',
      location: 'New York, NY, United States',
      employee_count: '180-300',
      revenue_estimate: '$32M ARR',
    },
    requirement: {
      title: 'Real-time AML monitoring & synthetic identity fraud detection',
      description:
        'Seeking an autonomous transaction monitoring platform to detect synthetic identity fraud and anomalous ledger movements in real-time before our upcoming FINRA regulatory audit.',
      requirement_type: 'AML & Fraud Prevention',
      urgency: 'High',
      budget_hint: '$60k - $90k ARR',
    },
    source: {
      platform: 'Public RFP Portal',
      original_url: 'https://procurement.fintech-leads.demo/rfp/aml-2026-081',
      verified_public: true,
      confidence_score: 0.97,
    },
    detected_date: '2026-03-09T08:15:00Z',
    intent_level: 'High',
    match_score: 96,
    matched_offering: 'PulseSentry AML & Real-time Identity Detector',
    match_rationale:
      'Urgent regulatory deadline requiring automated transaction monitoring and sub-10ms synthetic identity verification across payment rails.',
    status: 'New',
  },
  {
    id: 'disc-003',
    company: {
      name: 'FinTrack Analytics',
      domain: 'fintrack.io',
      industry: 'FinTech / Financial Data',
      location: 'San Francisco, CA, United States',
      employee_count: '180',
      revenue_estimate: '$28M ARR',
    },
    requirement: {
      title: 'SOC 2 Type II audit automation & AWS multi-account IAM governance',
      description:
        'Urgent requirement for automated auditor evidence collection and least-privilege IAM right-sizing to unblock two pending Tier-1 enterprise banking contracts.',
      requirement_type: 'Compliance & Security Posture',
      urgency: 'High',
      budget_hint: '$35k - $50k ARR',
    },
    source: {
      platform: 'B2B Procurement Feed',
      original_url: 'https://techprocure.demo/rfp/soc2-fintrack-492',
      verified_public: true,
      confidence_score: 0.95,
    },
    detected_date: '2026-03-07T14:20:00Z',
    intent_level: 'High',
    match_score: 95,
    matched_offering: 'AuditBot 360 & CloudArmor Posture Guard',
    match_rationale:
      'Series B funded scaleup with immediate compliance roadblock; requires automated evidence gathering and agentic Terraform remediation.',
    status: 'New',
  },
  {
    id: 'disc-004',
    company: {
      name: 'HealthBridge Care',
      domain: 'healthbridge.co',
      industry: 'Healthcare & Telehealth',
      location: 'Boston, MA, United States',
      employee_count: '320',
      revenue_estimate: '$45M ARR',
    },
    requirement: {
      title: 'European GDPR data residency & ISO 27001 telehealth readiness',
      description:
        'RFP for pre-certified ISO 27001 evidence automation and cross-border GDPR health data sovereignty monitoring for European telehealth clinic expansion.',
      requirement_type: 'Compliance & Data Sovereignty',
      urgency: 'High',
      budget_hint: '$40k - $60k ARR',
    },
    source: {
      platform: 'Public Regulatory Filing',
      original_url: 'https://regulatory-filings.health.demo/notices/iso-gdpr-2026',
      verified_public: true,
      confidence_score: 0.91,
    },
    detected_date: '2026-03-06T11:00:00Z',
    intent_level: 'High',
    match_score: 92,
    matched_offering: 'AuditBot 360 (Healthcare/ISO Edition)',
    match_rationale:
      'Strict regulatory timetable for clinical operation in Germany and France with heavy data privacy requirements.',
    status: 'New',
  },
  {
    id: 'disc-005',
    company: {
      name: 'DataSpire Systems',
      domain: 'dataspire.com',
      industry: 'Enterprise Data & Analytics',
      location: 'Austin, TX, United States',
      employee_count: '540',
      revenue_estimate: '$80M ARR',
    },
    requirement: {
      title: 'Automated cloud IAM role right-sizing & toxic permission mapping',
      description:
        'Experiencing cloud IAM role explosion following AWS multi-account migration. Need agentless visibility into dormant credentials and automated least-privilege role right-sizing.',
      requirement_type: 'Cloud Security & IAM',
      urgency: 'Medium',
      budget_hint: '$30k - $45k ARR',
    },
    source: {
      platform: 'Open B2B Procurement Portal',
      original_url: 'https://openrfp.cloudinfra.demo/req/dataspire-iam-03',
      verified_public: true,
      confidence_score: 0.88,
    },
    detected_date: '2026-03-05T16:00:00Z',
    intent_level: 'Medium',
    match_score: 88,
    matched_offering: 'Zero-Trust Identity Sentinel (CIEM)',
    match_rationale:
      'Operational bottleneck caused by over-privileged roles and lack of cross-account IAM visibility.',
    status: 'New',
  },
  {
    id: 'disc-006',
    company: {
      name: 'OmniRetail Global',
      domain: 'omniretail.com',
      industry: 'E-Commerce & Retail Tech',
      location: 'London, United Kingdom',
      employee_count: '850',
      revenue_estimate: '$120M ARR',
    },
    requirement: {
      title: 'Continuous multi-cloud audit readiness ahead of Q4 IPO',
      description:
        'Board audit committee mandated continuous multi-cloud security monitoring and automated evidence collection across AWS and Azure environments before IPO filing.',
      requirement_type: 'Compliance & Audit',
      urgency: 'High',
      budget_hint: '$50k - $80k ARR',
    },
    source: {
      platform: 'Public Corporate Tender Portal',
      original_url: 'https://tenders.omni.demo/rfp/ipo-audit-readiness',
      verified_public: true,
      confidence_score: 0.93,
    },
    detected_date: '2026-03-08T09:00:00Z',
    intent_level: 'High',
    match_score: 91,
    matched_offering: 'AuditBot 360 & Posture Guard Enterprise',
    match_rationale:
      'Hard deadline driven by public IPO filing with external auditor committee scrutiny.',
    status: 'New',
  },
];

export const MOCK_STRUCTURED_PROFILE: StructuredBusinessProfile = {
  company_name: 'CloudArmor AI',
  company_website: 'https://cloudarmor.ai',
  company_summary:
    'CloudArmor AI delivers an autonomous cloud security and continuous compliance platform that continuously monitors AWS, GCP, and Kubernetes for misconfigurations, detects least-privilege IAM risks, and automates 90% of SOC 2, ISO 27001, and HIPAA audit evidence gathering.',
  products_services: [
    'CloudArmor Posture Guard (CSPM)',
    'AuditBot 360 (Automated Compliance)',
    'Zero-Trust Identity Sentinel (CIEM)',
  ],
  target_customers: [
    'VP of Information Security / CISO',
    'CTO & VP of Engineering',
    'Head of Infrastructure & SecOps',
    'DevSecOps / Compliance Leads',
  ],
  target_industries: [
    'Fintech & RegTech',
    'Healthcare & Telemedicine',
    'B2B Enterprise SaaS',
    'AI & Autonomous Systems',
  ],
  target_locations: [
    'North America (US, Canada)',
    'European Union (UK, Germany, France)',
    'Global Remote-First Organizations',
  ],
  ideal_customer_profile:
    'Series A to Pre-IPO tech scaleups with 40-1,000 employees running multi-account cloud environments, facing upcoming enterprise audits, and seeking to unblock revenue stalled on compliance reviews.',
  keywords: [
    'cloud posture management',
    'automated SOC 2 evidence',
    'agentic terraform PRs',
    'least privilege IAM',
    'HIPAA audit acceleration',
    'continuous cloud compliance',
  ],
  buying_signals: [
    'Series A/B/C funding round announced (> $15M raised)',
    'Active hiring for Head of Security or DevOps engineers',
    'Enterprise deals blocked pending SOC 2 / ISO audit certification',
    'European geographic expansion requiring GDPR & ISO compliance',
    'Cloud migration or multi-account infrastructure restructuring',
  ],
  is_demo_mode: true,
  source_files: ['CloudArmor_Architecture_Whitepaper_2026.pdf'],
  updated_at: '2026-03-08T12:00:00Z',
};

export const MOCK_BUSINESS_PROFILE: BusinessProfile = {
  id: 'biz-cloudarmor',
  company_name: 'CloudArmor AI',
  domain: 'cloudarmor.ai',
  industry: 'Cybersecurity & Cloud Infrastructure',
  headline: 'Autonomous Cloud Security & Continuous Compliance for High-Growth Scaleups',
  description:
    'CloudArmor AI delivers an agentic cloud security platform that continuously monitors AWS, GCP, and Kubernetes for configuration drift, enforces zero-trust identity policies, and automates 90% of SOC 2, ISO 27001, and HIPAA compliance audit evidence.',
  value_propositions: [
    'Cut compliance audit preparation time from 4 months to under 10 days.',
    'Autonomous remediation of cloud posture risks before auditors or attackers notice.',
    'Unified agentless visibility across multi-cloud environments in 15 minutes.',
    'Eliminate redundant legacy security tooling with an all-in-one platform.',
  ],
  differentiators: [
    'Agentic Remediation: Generates verified Infrastructure-as-Code (Terraform) PRs to fix security issues.',
    'Native LLM Copilot: Translates complex IAM permissions and compliance clauses into human explanations.',
    'Fastest Time-to-Value: Zero-agent API integration with AWS/GCP/Kubernetes in under 15 minutes.',
  ],
  products: [
    {
      id: 'prod-cspm',
      name: 'CloudArmor Posture Guard',
      category: 'Cloud Security Posture Management (CSPM)',
      tagline: 'Agentless multi-cloud visibility and automated drift remediation',
      description:
        'Continuously audits multi-cloud assets against 400+ CIS benchmarks and security standards with 1-click auto-remediation.',
      key_features: [
        'Multi-cloud agentless asset inventory',
        'Continuous CIS Benchmark scanning',
        'Automated Terraform pull request generation',
        'Real-time misconfiguration alerts',
      ],
      target_pain_points: [
        'Manual security reviews slowing down deployments',
        'Blind spots in sprawling cloud resources',
        'Engineers overwhelmed by false-positive security alerts',
      ],
      pricing_tier: 'Starting at $18,000 / year',
      ideal_customer_size: '50 - 1,000 employees',
      proof_point: 'Reduced cloud vulnerability backlog by 74% in 30 days for Series B Fintechs.',
    },
    {
      id: 'prod-auditbot',
      name: 'AuditBot 360',
      category: 'Continuous Compliance & Audit Automation',
      tagline: 'Automate 90% of SOC 2, ISO 27001, and HIPAA evidence gathering',
      description:
        'AI compliance copilot that links cloud infrastructure, HRIS, and developer tools to automatically gather auditor-grade evidence 24/7.',
      key_features: [
        'Instant evidence generation for SOC 2 Type II and ISO 27001',
        'Continuous vendor risk and employee device monitoring',
        'Pre-built auditor portal with read-only verification logs',
        'Custom policy template generation using AI',
      ],
      target_pain_points: [
        'Engineering teams wasting hundreds of hours on manual audit screenshots',
        'Deal slippage caused by slow security questionnaire responses',
        'Upcoming enterprise customer security reviews',
      ],
      pricing_tier: 'Starting at $24,000 / year',
      ideal_customer_size: '40 - 500 employees',
      proof_point: 'Helped 120+ SaaS startups achieve clean SOC 2 Type II reports in 14 days.',
    },
    {
      id: 'prod-ciem',
      name: 'Zero-Trust Identity Sentinel',
      category: 'Cloud Identity & Entitlement Management (CIEM)',
      tagline: 'Least-privilege cloud IAM enforcement without breaking prod',
      description:
        'AI-driven identity analytics that discovers dormant permissions, toxic combinations, and over-privileged service accounts across cloud roles.',
      key_features: [
        'Toxic permission combination mapping',
        'Automated least-privilege role right-sizing',
        'Just-in-time (JIT) temporary privilege escalation',
        'Machine identity and API key governance',
      ],
      target_pain_points: [
        'Over-privileged IAM roles creating blast-radius risks',
        'Dormant contractor and former employee credentials',
        'Complex Kubernetes RBAC and cross-account access',
      ],
      pricing_tier: 'Starting at $32,000 / year',
      ideal_customer_size: '100 - 2,500 employees',
      proof_point: 'Prevented credential blast radius escalation in 45 enterprise Kubernetes clusters.',
    },
  ],
  target_personas: [
    {
      id: 'per-ciso',
      title: 'VP of Information Security / CISO',
      seniority: 'Executive',
      department: 'Security & Governance',
      key_priorities: [
        'Passing upcoming enterprise audit deadlines without drama',
        'Consolidating security vendors to reduce operational overhead',
        'Proving cybersecurity ROI to the Board of Directors',
      ],
      common_objections: [
        'We already use AWS native tools like Security Hub and GuardDuty',
        'We don’t have engineering cycles to install and maintain another agent',
        'Budget is frozen until next fiscal quarter',
      ],
    },
  ],
  collateral_docs: [
    'CloudArmor_Architecture_Whitepaper_2026.pdf',
    'SOC2_Acceleration_CaseStudy_FinTrack.pdf',
  ],
};

export const MOCK_SIGNALS: BuyingSignal[] = [
  {
    id: 'sig-001',
    company_name: 'FinTrack Analytics',
    domain: 'fintrack.io',
    signal_type: 'funding',
    title: 'Closed $38M Series B Funding Round led by Bessemer',
    summary:
      'FinTrack raised $38M to scale their real-time financial ledger API and expand into Tier 1 banking clients.',
    source: 'TechCrunch & Crunchbase',
    detected_at: '2026-03-01T10:15:00Z',
    confidence_score: 0.96,
    urgency_level: 'High',
    urgency_score: 94,
    processed: true,
    lead_id: 'lead-001',
  },
  {
    id: 'sig-002',
    company_name: 'FinTrack Analytics',
    domain: 'fintrack.io',
    signal_type: 'hiring_surge',
    title: 'Actively hiring Head of Information Security & 4 Senior DevOps Engineers',
    summary:
      'FinTrack posted job openings specifically requiring SOC 2 Type II experience and AWS multi-account governance.',
    source: 'LinkedIn Talent Insights',
    detected_at: '2026-03-03T14:20:00Z',
    confidence_score: 0.92,
    urgency_level: 'High',
    urgency_score: 91,
    processed: true,
    lead_id: 'lead-001',
  },
  {
    id: 'sig-003',
    company_name: 'HealthBridge Care',
    domain: 'healthbridge.co',
    signal_type: 'expansion',
    title: 'Announced EU Expansion & Telehealth Clinic Rollout',
    summary:
      'HealthBridge is launching telehealth services in Germany and France, requiring immediate GDPR and ISO 27001 certification.',
    source: 'Press Release & Regulatory Filing',
    detected_at: '2026-03-04T09:00:00Z',
    confidence_score: 0.89,
    urgency_level: 'High',
    urgency_score: 88,
    processed: true,
    lead_id: 'lead-002',
  },
  {
    id: 'sig-004',
    company_name: 'DataSpire Systems',
    domain: 'dataspire.com',
    signal_type: 'tech_stack_change',
    title: 'Migrated Core Data Warehouse from On-Premises to AWS Multi-Account',
    summary:
      'CTO published a technical engineering blog discussing complex cloud IAM role explosion during AWS migration.',
    source: 'Engineering Blog & GitHub',
    detected_at: '2026-03-05T16:45:00Z',
    confidence_score: 0.85,
    urgency_level: 'Medium',
    urgency_score: 76,
    processed: true,
    lead_id: 'lead-003',
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-001',
    company_name: 'FinTrack Analytics',
    domain: 'fintrack.io',
    industry: 'Fintech / Financial Data',
    employee_count: '180',
    estimated_revenue: '$28M ARR',
    location: 'San Francisco, CA & Remote',
    tech_stack: ['AWS', 'Kubernetes', 'PostgreSQL', 'Terraform', 'GitHub Actions'],
    signals_count: 2,
    signals_summary: [
      'Series B $38M funding led by Bessemer (High Urgency)',
      'Urgent hiring for Head of Security & DevOps with SOC 2 mandate',
    ],
    contacts: [
      {
        name: 'Marcus Vance',
        title: 'VP of Engineering & Acting Head of Security',
        role_level: 'VP',
        email: 'm.vance@fintrack.io',
        phone: '+1 (415) 890-3412',
        linkedin_url: 'https://linkedin.com/in/marcus-vance-fintrack',
        decision_authority: 'Primary',
      },
    ],
    primary_contact: {
      name: 'Marcus Vance',
      title: 'VP of Engineering & Acting Head of Security',
      role_level: 'VP',
      email: 'm.vance@fintrack.io',
      phone: '+1 (415) 890-3412',
      linkedin_url: 'https://linkedin.com/in/marcus-vance-fintrack',
      decision_authority: 'Primary',
    },
    match: {
      product_id: 'prod-auditbot',
      product_name: 'AuditBot 360',
      fit_score: 96,
      match_tier: 'Strong',
      reasoning:
        'FinTrack’s recent $38M round and enterprise banking expansion require fast SOC 2 Type II certification.',
      aligned_features: [
        'Automated SOC 2 Type II evidence gathering',
        'Continuous AWS multi-account scanning',
        'Direct auditor portal integration',
      ],
      suggested_pitch:
        'Help FinTrack secure Tier 1 banking contracts without taking 4 months of engineering time to pass SOC 2 Type II.',
    },
    intent: {
      overall_score: 94,
      grade: 'A',
      urgency_component: 95,
      fit_component: 98,
      authority_component: 90,
      timing_component: 92,
      buying_readiness: 'Immediate (0-30 days)',
      key_drivers: [
        'Fresh capital deployment ($38M Series B)',
        'Active job req for security leadership with immediate audit deliverables',
        'Enterprise customers blocking deals pending SOC 2 report',
      ],
    },
    status: 'Interested',
    created_at: '2026-03-01T12:00:00Z',
    updated_at: '2026-03-08T09:30:00Z',
    notes: 'Engaged with AI Sales Agent. Agreed to technical demo.',
  },
  {
    id: 'lead-002',
    company_name: 'HealthBridge Care',
    domain: 'healthbridge.co',
    industry: 'Healthcare / Telemedicine',
    employee_count: '320',
    estimated_revenue: '$45M ARR',
    location: 'Boston, MA',
    tech_stack: ['GCP', 'Kubernetes', 'React Native', 'BigQuery', 'Terraform'],
    signals_count: 1,
    signals_summary: ['Announced EU expansion needing ISO 27001 and GDPR compliance'],
    contacts: [
      {
        name: 'Dr. Aris Thorne',
        title: 'Chief Technology Officer',
        role_level: 'C-Level',
        email: 'aris.thorne@healthbridge.co',
        phone: '+1 (617) 555-0192',
        linkedin_url: 'https://linkedin.com/in/aris-thorne',
        decision_authority: 'Primary',
      },
    ],
    primary_contact: {
      name: 'Dr. Aris Thorne',
      title: 'Chief Technology Officer',
      role_level: 'C-Level',
      email: 'aris.thorne@healthbridge.co',
      phone: '+1 (617) 555-0192',
      linkedin_url: 'https://linkedin.com/in/aris-thorne',
      decision_authority: 'Primary',
    },
    match: {
      product_id: 'prod-auditbot',
      product_name: 'AuditBot 360',
      fit_score: 91,
      match_tier: 'Strong',
      reasoning:
        'Expanding into European telehealth requires ISO 27001 & GDPR audit compliance within 90 days.',
      aligned_features: ['ISO 27001 automation', 'GDPR data residency monitoring', 'HIPAA cross-walk'],
      suggested_pitch:
        'Fast-track HealthBridge’s European clinic launch with pre-certified ISO 27001 auditor packages.',
    },
    intent: {
      overall_score: 88,
      grade: 'A',
      urgency_component: 90,
      fit_component: 92,
      authority_component: 88,
      timing_component: 84,
      buying_readiness: 'High (30-60 days)',
      key_drivers: [
        'Strict regulatory deadline for German & French clinic operations',
        'High sensitivity to healthcare data breaches',
      ],
    },
    status: 'Outreach_Ready',
    created_at: '2026-03-04T10:00:00Z',
    updated_at: '2026-03-07T14:15:00Z',
  },
  {
    id: 'lead-003',
    company_name: 'DataSpire Systems',
    domain: 'dataspire.com',
    industry: 'Enterprise Data / Analytics',
    employee_count: '540',
    estimated_revenue: '$80M ARR',
    location: 'Austin, TX',
    tech_stack: ['AWS', 'Snowflake', 'Databricks', 'Kubernetes', 'Okta'],
    signals_count: 1,
    signals_summary: [
      'Migrated to AWS multi-account; blogged about cloud IAM permission explosion',
    ],
    contacts: [
      {
        name: 'Kavita Raman',
        title: 'Head of Cloud Infrastructure & SecOps',
        role_level: 'Director',
        email: 'k.raman@dataspire.com',
        phone: '+1 (512) 441-9081',
        decision_authority: 'Influencer',
      },
    ],
    primary_contact: {
      name: 'Kavita Raman',
      title: 'Head of Cloud Infrastructure & SecOps',
      role_level: 'Director',
      email: 'k.raman@dataspire.com',
      phone: '+1 (512) 441-9081',
      decision_authority: 'Influencer',
    },
    match: {
      product_id: 'prod-ciem',
      product_name: 'Zero-Trust Identity Sentinel',
      fit_score: 94,
      match_tier: 'Strong',
      reasoning:
        'DataSpire explicitly mentioned IAM role explosion and toxic privilege paths in their AWS multi-account environment.',
      aligned_features: [
        'Toxic permission mapping',
        'Least-privilege role right-sizing',
        'Okta-to-AWS role sync',
      ],
      suggested_pitch:
        'Automatically prune dormant permissions and enforce least-privilege IAM across AWS multi-account organizations without breaking production.',
    },
    intent: {
      overall_score: 84,
      grade: 'B',
      urgency_component: 80,
      fit_component: 95,
      authority_component: 82,
      timing_component: 78,
      buying_readiness: 'High (30-60 days)',
      key_drivers: [
        'Publicly acknowledged operational bottleneck around cloud IAM',
        'High security posture requirement handling enterprise client telemetry',
      ],
    },
    status: 'Matched',
    created_at: '2026-03-05T17:00:00Z',
    updated_at: '2026-03-06T11:00:00Z',
  },
  {
    id: 'lead-004',
    company_name: 'PayMatrix Global',
    domain: 'paymatrix.net',
    industry: 'Payments / RegTech',
    employee_count: '850',
    estimated_revenue: '$140M ARR',
    location: 'New York, NY',
    tech_stack: ['AWS', 'Azure', 'Kubernetes', 'Kafka', 'Datadog'],
    signals_count: 1,
    signals_summary: [
      'Appointed new CRSO tasked with Zero Trust modernization and hybrid posture',
    ],
    contacts: [
      {
        name: 'Elena Rostova',
        title: 'Chief Risk & Security Officer',
        role_level: 'C-Level',
        email: 'elena.rostova@paymatrix.net',
        phone: '+1 (212) 779-1102',
        decision_authority: 'Primary',
      },
    ],
    primary_contact: {
      name: 'Elena Rostova',
      title: 'Chief Risk & Security Officer',
      role_level: 'C-Level',
      email: 'elena.rostova@paymatrix.net',
      phone: '+1 (212) 779-1102',
      decision_authority: 'Primary',
    },
    match: {
      product_id: 'prod-cspm',
      product_name: 'CloudArmor Posture Guard',
      fit_score: 87,
      match_tier: 'Strong',
      reasoning:
        'New CRSO Elena is revamping vendor risk and hybrid cloud visibility following recent corporate acquisition.',
      aligned_features: [
        'Unified AWS and Azure security posture',
        'Agentic Terraform remediation',
        'Executive board reporting',
      ],
      suggested_pitch:
        'Give the executive board 100% real-time posture visibility across newly merged AWS & Azure accounts.',
    },
    intent: {
      overall_score: 81,
      grade: 'B',
      urgency_component: 82,
      fit_component: 88,
      authority_component: 92,
      timing_component: 72,
      buying_readiness: 'Exploring (60-90 days)',
      key_drivers: [
        'First 90-day executive mandate to review security toolchain',
        'Large enterprise budget availability',
      ],
    },
    status: 'Enriched',
    created_at: '2026-03-06T12:00:00Z',
    updated_at: '2026-03-07T16:00:00Z',
  },
];

export const MOCK_CALLS: CallSession[] = [];

export const MOCK_OPPORTUNITIES: Opportunity[] = [];

export const MOCK_OVERVIEW: DashboardOverview = {
  kpis: {
    active_buying_signals: 0,
    high_urgency_signals: 0,
    total_leads: 0,
    grade_a_leads: 0,
    ai_calls_conducted: 0,
    meetings_secured: 0,
    qualified_opportunities: 0,
    pipeline_value_estimate: '$0',
    average_response_rate: '0%',
    ai_qualification_rate: '0%',
  },
  funnel: [
    { stage: 'Signals Ingested', count: 0, percentage: 0 },
    { stage: 'Leads Enriched', count: 0, percentage: 0 },
    { stage: 'AI Matched', count: 0, percentage: 0 },
    { stage: 'AI Outreach', count: 0, percentage: 0 },
    { stage: 'Qualified', count: 0, percentage: 0 },
    { stage: 'CRM Deals', count: 0, percentage: 0 },
  ],
  top_buying_signals: [],
  high_priority_leads: [],
  recent_opportunities: [],
};
